[global]
disableWidgetStateDuplicationWarning = false
showWarningOnDirectExecution = false

[theme]
base = "light"
primaryColor = "#eedccb"
secondaryBackgroundColor = "#0083B8"



[client]
showErrorDetails = true
showSidebarNavigation = true
toolbarMode = "viewer"

[runner]
fastReruns = true

[secrets]
files = [ "~/.streamlit/secrets.toml"]