[global]
disableWidgetStateDuplicationWarning = false
showWarningOnDirectExecution = true

[theme]
base = "light"
primaryColor = "#46A748"


[client]
showErrorDetails = true
showSidebarNavigation = true

[runner]
fastReruns = true

[secrets]
files = [ "~/.streamlit/secrets.toml"]