[global]
disableWidgetStateDuplicationWarning = false
showWarningOnDirectExecution = false

[theme]
base = "light"
primaryColor = "#eedccb"
secondaryBackgroundColor = "#F5F5F5"



[client]
showErrorDetails = true
showSidebarNavigation = true
toolbarMode = "viewer"

[runner]
fastReruns = true

[secrets]
files = [ "~/.streamlit/secrets.toml"]